### ISSUE TITLE
surveys_egr: add usgss

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gender_roles#10]
https://www.icpsr.umich.edu/web/ICPSR/studies/36797

**Comment by byngdeuk** [comment]
This can be closed after a review from Lindsey and our discussion.

**Comment by fsolt** [comment]
where can I find these items?

**Comment by byngdeuk** [comment]
In the following link: https://www.icpsr.umich.edu/web/ICPSR/studies/36797/datadocumentation, we can get codebook and series of data files in different forms!
Data files are large (3GB).

**Comment by fsolt** [comment]
Right.  I mean: this survey is not yet included in surveys_egr.  Your [first comment](https://github.com/fsolt/dcpo_gender_roles/issues/10#issuecomment-664994182) suggests that you've completed it.  Can you add the items from this survey to surveys_egr, or point me to where I can find them?

**Comment by byngdeuk** [comment]
Oh I understand it! I will update it right away.

**Comment by byngdeuk** [comment]
I added items on the following link: https://github.com/fsolt/dcpo_gender_roles/blob/master/data-raw/surveys_egr.csv.
I'm still working on pgss. It will be done before our meeting!

**Comment by fsolt** [comment]
Thanks, Byung-Deuk!

**Comment by fsolt** [comment]
These three are factual knowledge questions, not normative, so I'm dropping them:

usgss | armedforce2a | fefight | c(2:1)
usgss | armedforce2b | fedirty | c(2:1)
usgss | armedforce2c | febrass | c(2:1)


usgss | FEFIGHT | As far as you know, are women now assigned to jobs in the armed forces that would expose them to combat, or are women not assigned to such jobs? | job | 1 Yes, they are / 2 No, they are not | https://www.icpsr.umich.edu/web/ICPSR/studies/36797
usgss | FEDIRTY | As far as you know, are women in the armed forces now assigned to dirty jobs like repairing trucks or other heavy equipment, or are women not assigned to such jobs? | job | 1 Yes, they are / 2 No, they are not | https://www.icpsr.umich.edu/web/ICPSR/studies/36797
usgss | FEBRASS | As far as you know, are women in the armed forces now assigned to jobs where they have command over men, or are women not assigned to such jobs? | job | 1 Yes, they are / 2 No, they are not | https://www.icpsr.umich.edu/web/ICPSR/studies/36797

**Comment by byngdeuk** [comment]
Thanks for rechecking my work! I will make sure to reduce my mistake in the next task.

**Comment by fsolt** [comment]
It's hard work.  It's good that we can go over it multiple times.  You've made the process of double-checking easy by documenting what you've done in gender_role_items.  Thanks for putting in so much effort!

**Comment by fsolt** [comment]
I'm going to drop this one on positive vs normative grounds, too:

usgss | born5 | opsex | c(1:5)

usgss | OPSEX | Being born a man or a woman -- how important is that for getting ahead in life? | born | 1 Essential / 5 Not important at all | https://www.icpsr.umich.edu/web/ICPSR/studies/36797
