### ISSUE TITLE
surveys_egr: add jgss

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gender_roles#11]
https://www.icpsr.umich.edu/web/ICPSR/studies/04472

**Comment by byngdeuk** [comment]
Finished. This can be closed :).

**Comment by fsolt** [comment]
Quick work!  Note that 04472-0002-Codebook.pdf at 279 has a variable crosswalk with the usgss variables (helpful given the incomplete question translations)

**Comment by byngdeuk** [comment]
Great! I will add full questionnaires in the "Question Text" Column.

**Comment by fsolt** [comment]
2005: https://search.gesis.org/research_data/ZA4270
2006: https://search.gesis.org/research_data/ZA4873
2008: https://search.gesis.org/research_data/ZA5294
2010: https://search.gesis.org/research_data/ZA5352
2012: https://search.gesis.org/research_data/ZA6427

**Comment by fsolt** [comment]
see also https://github.com/fsolt/DCPOtools/issues/40
