### ISSUE TITLE
surveys_egr: add kgss

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gender_roles#12]
http://kgss.skku.edu/wp-content/uploads/2018/10/2003-2016_KGSS_ENG_09302018.sav_.zip 
http://kgss.skku.edu/wp-content/uploads/2018/10/2003-2016-KGSS-Cumulative-Code-Book_09302018.pdf

**Comment by byngdeuk** [comment]
The second link does not work. 
Thus, I select appropriate questions based on the labels in the  ".sav" file.

**Comment by byngdeuk** [comment]
Some labels are not full sentences. For example, "Opinions on gender roles: It is more important for a wife to help her husband's".
I guess that the full sentence may be ".... for a wife to help her husband's work (etc.)"
Could I include those variables without full sentenced labels?

**Comment by fsolt** [comment]
From surveys_egr, I'm pulling out

kgss | jobinde5 | fewrksup | c(5:1)


kgss | FEWRKSUP | Agree or disagree most women have to work to support the family | work support | 1 Strongly Agree / 5 Strongly Disagree | http://kgss.skku.edu/wp-content/uploads/2018/10/2003-2016_KGSS_ENG_09302018.sav_.zip

for two reasons: first, this isn't the same question as jobinde5 has been used for above 

kgss | FEJOBIND | Agree or disagree having a job is a best way for a woman to be independent | job independence | 1 Strongly Agree / 5 Strongly Disagree | http://kgss.skku.edu/wp-content/uploads/2018/10/2003-2016_KGSS_ENG_09302018.sav_.zip

second, I'm not just relabeling it something else because I think the question of whether women "have to" work to support the family is more positive than normative--traditionalists likely agree it is true even if they lament the fact.  (I have a riff in 1400 about how U.S. Republicans abolished joint taxation on family values grounds--it discourages working couples from marrying, they said--while German Christian Democrats continued to champion it 'cause it keeps wives at home.  U.S. traditionalists would apparently agree with this question.)

**Comment by byngdeuk** [comment]
I understand and I agree to leave them out!
