### ISSUE TITLE
paper: needs introduction

### ISSUE THREAD

**Issue by byngdeuk** [fsolt/dcpo_gender_roles#16]
This is note for the last meeting and the goal to achieve in the Intro Section.
something about sorts of questions could be answered if we use our data.
literature review what existing works it is about public opinion in this field. Some discussions about database already existing.

**Comment by fsolt** [comment]
One possibly useful angle: https://twitter.com/jennpiscopo/status/1291833593191206912?s=11

<img width="593" alt="Screen Shot 2020-08-08 at 8 49 16 AM" src="https://user-images.githubusercontent.com/6536645/89712119-64369380-d954-11ea-85c8-5c51be3cc69e.png">

**Comment by byngdeuk** [comment]
My question or suggestion: I think we should mention the definition of gender egalitarianism. After literature review, I realize that there is some variation in the definition of gender egalitarianism. I think we need to think about our definition of gender egalitarianism.

Bernard’s definition of gender role: Gender toles, the constellation of traits and behaviors which are “feminine” and “masculine,” vary across cultures and times; for example, it is masculine in some societies for men to be highly emotional and sensitive (Bernard, p.2).

**Comment by byngdeuk** [comment]
[DCPO Introduction.docx](https://github.com/fsolt/dcpo_gender_roles/files/5052497/DCPO.Introduction.docx)

**Comment by byngdeuk** [comment]
I uploaded my version of the introduction part. Lindsey also will upload her version before our meeting tomorrow. 
In my version, I did not yet modify the style and also the file is written in word which is bad..
After our discussion in the next meeting, I will change it to R-Markdown version. 

I try to include an article published in APSR. But, the article is too old (1974).

After writing this part, I think that our work is amazing and promising. There are literary no time-series cross-national index for the egalitarian gender role even though there are so many interesting questions :)!

**Comment by lallemang** [comment]
I'm sorry it's taken me a while to get this uploaded post-Derecho. My focus has shifted entirely to comps and preparing for the beginning of the semester over this past week. I'm uploading my draft of the introduction as I described in my email to you both last week. At some point, Byung-Deuk and I will need to work on merging our drafts so they flow nicely together.

@fsolt Do you think we will have estimates to work with by the end of comps week? I am hoping to immediately transition to finishing my paper after the exams next week, but I will need those to move forward. 

Thank you to you both for all of your help and hard work this summer! It has been an exceptionally difficult past few months, but I am excited to continue working on this project and see where it takes us.
[DCPO paper introduction.docx](https://github.com/fsolt/dcpo_gender_roles/files/5104125/DCPO.paper.introduction.docx)

**Comment by fsolt** [comment]
@lallemang Oh, we've got estimates now.  See [the data/ directory](https://github.com/fsolt/dcpo_gender_roles/tree/master/data) as well as the [last figure in the latest draft]( https://github.com/fsolt/dcpo_gender_roles/blob/master/paper/dcpo_gender_roles.pdf).

**Comment by fsolt** [comment]
I suppose I should add that, in our discussion Tuesday, we talked about possibly revising these estimates, but in any event, there's data to start with.

**Comment by byngdeuk** [comment]
I add rmd and bib files to the following link https://github.com/fsolt/dcpo_gender_roles/tree/master/paper!
I combine my version of intro and Lindsey's one into the one introduction.

**Comment by fsolt** [comment]
Just quickly noting what came out of today's meeting re the intro: it'll need a discussion of the four categories of gender equality questions we came up with, and it will need to be clear that we focus on the first, public, category.

**Comment by byngdeuk** [comment]
I got it!
I try to add some sentences for it.
