### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by byngdeuk** [fsolt/dcpo_gender_roles#19]
Gender role: 1) We need Inspiration - We can refer the APSR article from Caughey et. al. (2019). -> Maybe add Validation Section / DCPO has "validation function" both for internal and external.  2) Read the Caughey et. al. and think about how much validation is needed to be included. 
For validation check: 1) DCPO internal and external validation, 2) current attitudes as a predictor of women's descriptive representation in democratic countries, 3)We could do really simple (Existence of chief executive and public opinion

**Comment by byngdeuk** [comment]
Book: 1)Public Opinion and Women's descriptive representation, 2)Public Opinion and Policies about violence against women, 3)Public Opinion and Combat Role. - 1)Big Quantitative Studies, 2)Case Studies (Koreas, Britain, Eritrea, etc.)

**Comment by fsolt** [comment]
FLFPR and (college) education
