### ISSUE TITLE
surveys_egr: wvs

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gender_roles#20]
@Tyhcass points out that wvs7 doesn't necessarily include all the questions that the individual country files include.  Sigh.

**Comment by fsolt** [comment]
Also, the file has been updated with at least one more country, so re-running with the new file should give us more data

**Comment by Tyhcass** [comment]
Evs_combo does not include 10+ countries. You might want to add more individual countries.  I will update these countries for abortion. Then, you can check directly whether these countries had gender questions.  Also, chcep2018 has questions about gender egalitarianism, like "please tell me if you agree or disagree with the statement “The husband's duty is to earn money; duty of the woman is to take care of the house and the family....", you might want to check. @fsolt @byngdeuk
