### ISSUE TITLE
Good Comments from Reviewers (For Memo)

### ISSUE THREAD

**Issue by byngdeuk** [fsolt/dcpo_gender_roles#24]
Reviewer #1
1.	The manuscript is well written and the issue that they seek to address is clearly defined.  It is strongly situated on existing scholarship on the topic, which is of broad significance, and it follows a number of other projects that are using latent variable modeling to improve measures in comparative politics.  The dataset that they describe may be of interest to a more specific audience, but this seems an appropriate venue for its introduction.

Reviewer #2
1.	I think this is a good paper and I look forward to seeing it in print. I am unlikely to use their measure in my research (because I rarely do cross-national work) but I envision assigning this article to my students as an excellent example of a measurement paper (for undergrads) and an IRT model (for my grad students).
2.	In sum, I think this is a great measure and an impressive paper. I have some qualms with the writing itself, which I think can be simplified and explained more and which I have explained above, but otherwise I support accepting this paper.

**Comment by byngdeuk** [comment]
Related to the revised version of draft and appendix,
I like the way it is organized and reacted to the comments Fred!

**Comment by fsolt** [comment]
Okay, @byngdeuk, I think it's ready to go.  Please check [`dcpo_gender_roles.pdf`](https://github.com/fsolt/dcpo_gender_roles/blob/master/paper/dcpo_gender_roles.pdf) (which, astoundingly, is at just 3934 words), [`pge_appendix.pdf`](https://github.com/fsolt/dcpo_gender_roles/blob/master/paper/pge_appendix.pdf), and [`response_memo.pdf`](https://github.com/fsolt/dcpo_gender_roles/blob/master/paper/response_memo.pdf) and let me know your thoughts.

**Comment by byngdeuk** [comment]
Dear Fred,

I read the documents over and I totally agree with that we handle the reviewer's comments on our previous manuscript!
I'm really happy to our revised manuscript and I think it is ready to be resubmited:)!

Thanks!!

All My Best,
-Byung-Deuk.
