### ISSUE TITLE
Explanation about Surveys Employed in Our Paper

### ISSUE THREAD

**Issue by byngdeuk** [fsolt/dcpo_gender_roles#25]
Reviewer #1
1.	Though the Appendix (A) explains dispersion and difficulty, they should include some discussion or representation in the main text. One illustrative example is Figure 1 in Gandhi and Sumner (2020, "Measuring the Consolidation of Power in Nondemocracies"). The note should also consider adding more description about how the estimates were obtained (e.g., section 4.3 and 4.4 of Claassen 2018 or final paragraph before "Results" of Gandhi and Sumner 2020).

Reviewer #2
1.	Finally, a small but important point: It isn't entirely clear from the paper whether you are only using cross-national surveys or whether you also incorporate single-country surveys? (I'm mostly confused because of sentences such as "Country coverage reached its peak in 2008, when surveys in 78 countries included items on gender egalitarianism in the public sphere")

**Comment by fsolt** [comment]
R2: We clarified that we are drawing on both cross-national and single-country surveys at the top of page 2.  We also revised the sentence on peak country coverage in an attempt to avoid any confusion. c698e994855fd415d7a169efef3c9684d9c1b879

**Comment by fsolt** [comment]
R1's two points here really aren't related to each other or R2's point, so I split them off (see #30 and #31) and close this one, @byngdeuk.
