### ISSUE TITLE
Explanation about the Coverage of Estimates by Country

### ISSUE THREAD

**Issue by byngdeuk** [fsolt/dcpo_gender_roles#26]
Reviewer #1
1.	Based on summary statistics provided by the authors, the sample afforded by the coverage of survey items and the resulting scores--2695 country-year observations--would be roughly 45 percent of the possible sample of country-years if the 124 countries were all independent across that period (5,952). They also note that the United States has 140 item observations while Cambodia, Sri Lanka, and Suriname have 2. This should mean that the dataset would have limited applicability in cross-national time-series models due to listwise deletion (some countries would be better represented across time, while others would not). This is something that the authors do not discuss, and something that might be helped by providing a country-year plot that shows when estimates are available for each country and in each year (a scatterplot with year on the X-axis and country on the Y-axis, similar to Figure 1 in Claassen 2018, "Estimating Smooth Country-Year Panels of Public Opinion").
Relatedly, although it is a nice illustration, Figure 3 obscures where observations exist (it appears as if estimates are available for every year). If they are not, then the countries being illustrated are not equally comparable over time.

**Comment by fsolt** [comment]
R1 is confusing the source data coverage with the coverage of the estimates—the model is designed to provide continuous estimates even when the source data are sparse (and the cross-validations in Solt 2020a shows it does a good job of doing so).  This isn't a surprising take from people accustomed to complete data, so have to find a way to address it more explicitly.

**Comment by fsolt** [comment]
This is closely related to R1's comments on #27: whether there are only one or two source-data observations (#27), or zero (#26), the model is designed to generate estimates that are comparable

**Comment by fsolt** [comment]
Also, I suppose, re R1's comments on #28: if model was described more clearly, this would be more evident

**Comment by byngdeuk** [comment]
I totally agree.
