### ISSUE TITLE
Minor Language Issue

### ISSUE THREAD

**Issue by byngdeuk** [fsolt/dcpo_gender_roles#29]
Reviewer #1
1.	There is unclear language, e.g., "Viewed from this complete-data perspective..." (pg. 2)
2.	"The upper left panel shows the twelve countries with the most years observed" (pg. 3).  I believe that that should be "upper right."
3.	"...responses to particular questions in particular questions" (pg. 4)

**Comment by fsolt** [comment]
1.  Revised to "Compared to this complete set of country-year-items..."
2. Corrected to read "upper right."  Thanks for catching this, R1.
3. The repeated words have been excised.  Thanks for catching this, R1.
