### ISSUE TITLE
surveys_egr: add Asia Europe Survey

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gender_roles#5]
ases2000
https://www.icpsr.umich.edu/web/ICPSR/studies/22324

Now, I have some statements here that people make from time to time. Please tell me how much you agree or disagree with the following statements:
V0215 "A woman’s primary role is in the home"

**Comment by byngdeuk** [comment]
The following link https://www.icpsr.umich.edu/web/ICPSR/studies/22324 is about “Asia Europe Survey (ASES): A Multinational Comparative Study in 18 Countries, **2001**. Thus, I guess that the name of the survey should be **“ases2001”?** I think this is just a very very small problem, but I want to mention this thing.

**Comment by fsolt** [comment]
Thanks for the keen eye, Byung-Deuk; this is something I pondered myself.  The survey was actually conducted in 2000 in all included countries.  I ultimately decided to go with the accurate label instead of matching ICPSR's decision.
