### ISSUE TITLE
surveys_egr: check for surveys in pew global

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gender_roles#8]
https://www.pewresearch.org/global/question-search/

**Comment by byngdeuk** [comment]
Does "pew2002" equal to "Summer 2002 Survey Data" on the following link "https://www.pewresearch.org/global/dataset/summer-2002-survey-data/"?
There are April 2002, November 2002, and Summer 2002 Survey Data.
Only Summer 2002 Survey data includes questions about gender equality. 

Thus, I guess that "pew2002" is equal to "Summer 2002 Survey Data".
I want to make it clear :)

**Comment by fsolt** [comment]
Confirmed: per https://github.com/fsolt/DCPOtools/blob/master/data/surveys_data.csv#L485 (at `file_id`) `pew2002` is `summer-2002-survey-data`.
