### ISSUE TITLE
surveys_egr: check pew religion surveys

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gender_roles#9]
- [x] pewrel2006_10nat https://ropercenter.cornell.edu/ipoll/study/31085390 has good stuff to add at p32 of codebook

Please check these on [the Pew website](https://www.pewforum.org/datasets/) also (find them by year, on the right):

- [x] pewrel2009_afr
- [x] pewrel2014_latam
- [x] pewrel2014_us
- [x] pewrel2015_ee
- [x] pewrel2016_us
- [x] pewrel2017_we

**Comment by byngdeuk** [comment]
Is pewrel2014_us equal to "Pew Research Center 2014 U.S. Religious Landscape Study" or "American Trends Panel?
If it is "Pew Research Center 2014 U.S. Religious Landscape Study", I cannot locate "pewrel2016_us".

**Comment by byngdeuk** [comment]
Note: pewrel2014_us is for  "Pew Research Center 2014 U.S. Religious Landscape Study". pewrel2016_us is for "American Trends Panel wave 20".

**Comment by byngdeuk** [comment]
I overviewed questionnaires in "Pew Research Center 2014 U.S. Religious Landscape Study an" and "American Trends Panel wave 20". I think that there are no questionnaires we can include.
